---
- name: Create Audiobookshelf media directories
  ansible.builtin.file:
    path: /mnt/media-nvm/Audiobookshelf
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Copy Docker-compose file
  ansible.posix.synchronize:
    src: files/media/audiobookshelf/docker-compose.yml
    dest: /mnt/media-nvm/Audiobookshelf

- name: Run Audiobookshelf
  community.docker.docker_compose_v2:
    project_src: /mnt/media-nvm/Audiobookshelf
...