---
- name: Create ErsatzTV directories
  ansible.builtin.file:
    path: /mnt/media/ErsatzTv
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Copy Docker-compose file
  ansible.posix.synchronize:
    src: files/media/ersatztv/docker-compose.yml
    dest: /mnt/media/ErsatzTv

- name: Run ErsatzTv
  community.docker.docker_compose_v2:
    project_src: /mnt/media/ErsatzTv
...