---
- name: Create Kavita media directories
  ansible.builtin.file:
    path: /mnt/media-nvm/Kavita
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Upload Kavita cron script
  ansible.posix.synchronize:
    src: media/kavita/new_file_uploaded.sh
    dest: /mnt/media-nvm/Kavita/

- name: Create cronjob that every 5 minutes creates dirs for newly added pdf books
  ansible.builtin.cron:
    name: "Check for pdf & epub files"
    state: present
    minute: "*/5"
    job: "/bin/bash /mnt/media-nvm/Kavita/new_file_uploaded.sh"

- name: Copy Docker-compose file
  ansible.posix.synchronize:
    src: files/media/kavita/docker-compose.yml
    dest: /mnt/media-nvm/Kavita

- name: Run Kavita
  community.docker.docker_compose_v2:
    project_src: /mnt/media-nvm/Kavita
...