---
packages_to_remove:
  - podman
  - buildah

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin

jellyfin_media_dirs:
  - /mnt/media/Jellyfin/media/Movies
  - /mnt/media/Jellyfin/media/Shows
  - /mnt/media/Jellyfin/media/Concerts

jump_media_dirs:
  - /mnt/media/Jump/backgrounds
  - /mnt/media/Jump/favicon
  - /mnt/media/Jump/sites/icons

...