services:
  lubelogger:
    image: ghcr.io/hargata/lubelogger:v1.6.1
    container_name: lubelogger
    user: "1000:1000"
    healthcheck:
      test: [ "CMD", "sleep", "1" ]
    restart: unless-stopped
    labels:
      sablier.enable: true
      sablier.group: "lubelogger"
    networks:
      - sleepers
    volumes:
      - /mnt/media-nvm/LubeLogger/data:/App/data
      - /mnt/media-nvm/LubeLogger/keys:/root/.aspnet/DataProtection-Keys
    environment:
#      - LC_ALL=Spanish_Mexico.1252
      - LANG=en_US

networks:
  sleepers:
    external: true