---
- name: Create Caddy directories
  ansible.builtin.file:
    path: /mnt/media-nvm/Sablier/Caddy
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Copy Caddy Dockerfile
  ansible.posix.synchronize:
    src: 'sablier/caddy/Dockerfile'
    dest: /mnt/media-nvm/Sablier/Caddy

- name: Build Caddy image with sablier plugin
  community.docker.docker_image:
    name: "caddy-packituz"
    tag: "latest-with-sablier"
    build:
      path: /mnt/media-nvm/Sablier/Caddy
    source: build

- name: Setup Caddy file
  ansible.posix.synchronize:
    src: 'sablier/caddy/Caddyfile'
    dest: '/mnt/media-nvm/Sablier/Caddy/Caddyfile'

- name: Copy Docker-compose file
  ansible.posix.synchronize:
    src: files/sablier/docker-compose.yml
    dest: /mnt/media-nvm/Sablier

- name: Run Sablier and Caddy
  community.docker.docker_compose_v2:
    project_src: /mnt/media-nvm/Sablier
    recreate: always
...