---
- name: Create JDownloader2 media directories
  ansible.builtin.file:
    path: /mnt/media/JDownloader2
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Create .env file
  ansible.builtin.copy:
    dest: /mnt/media/JDownloader2/.env
    content: |
      WEB_AUTHENTICATION='1'
      SECURE_CONNECTION='1'
      WEB_AUTHENTICATION_USERNAME={{ jdownloader2_username }}
      WEB_AUTHENTICATION_PASSWORD={{ jdownloader2_password }}

- name: Copy Docker-compose file
  ansible.posix.synchronize:
    src: files/downloaders/jdownloader2/docker-compose.yml
    dest: /mnt/media/JDownloader2

- name: Run JDownloader2
  community.docker.docker_compose_v2:
    project_src: /mnt/media/JDownloader2
    recreate: always

...