---
- name: Create Transmission directories
  ansible.builtin.file:
    path: /mnt/media/Transmission
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Create app.env file
  ansible.builtin.copy:
    dest: /mnt/media/Transmission/app.env
    content: |
      PGUID='1000'
      PGID='1000'
      TZ='Etc/UTC'
      USER={{ transmission_user }}
      PASS={{ transmission_password }}

- name: Copy Docker-compose file
  ansible.posix.synchronize:
    src: files/downloaders/transmission/docker-compose.yml
    dest: /mnt/media/Transmission

- name: Run Transmission
  community.docker.docker_compose_v2:
    project_src: /mnt/media/Transmission
    recreate: always

...