---
- name: Create Dronegc directories
  ansible.builtin.file:
    path: /mnt/media-nvm/Dronegc
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Copy Docker-compose file
  ansible.posix.synchronize:
    src: files/base/dronegc/docker-compose.yml
    dest: /mnt/media-nvm/Dronegc

- name: Run Dronegc
  community.docker.docker_compose_v2:
    project_src: /mnt/media-nvm/Dronegc

...