---
- name: Create Jump directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'
    mode: '0755'
  loop: '{{ jump_media_dirs }}'

- name: Copy icons and configurations
  ansible.posix.synchronize:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
  loop:
    - { source: 'base/jump/icon.png', destination: '/mnt/media/Jump/favicon/' }
    - { source: 'base/jump/sites.json', destination: '/mnt/media/Jump/sites/' }
    - { source: 'base/jump/favicon/', destination: '/mnt/media/Jump/sites/icons/' }
    - { source: 'base/jump/backgrounds', destination: '/mnt/media/Jump/' }

- name: Copy Docker-compose file
  ansible.posix.synchronize:
    src: files/base/jump/docker-compose.yml
    dest: /mnt/media/Jump

- name: Run Jump
  community.docker.docker_compose_v2:
    project_src: /mnt/media/Jump
    recreate: always
...