---
- name: Create Rael directories
  ansible.builtin.file:
    path: /mnt/media-nvm/Rael
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Copy Docker-compose file
  ansible.posix.synchronize:
    src: files/base/rael/docker-compose.yml
    dest: /mnt/media-nvm/Rael

- name: Run Rael
  community.docker.docker_compose_v2:
    project_src: /mnt/media-nvm/Rael

...