services:
  navidrome:
    image: deluan/navidrome:0.60.2
    container_name: navidrome
    restart: unless-stopped
    ports:
      - "4533:4533"
    volumes:
      - /mnt/media-nvm/Navidrome/music:/music
      - /mnt/media-nvm/Navidrome/data:/data