services:
  cloudflare_tunnels:
    image: cloudflare/cloudflared:2026.2.0
    container_name: cloudflare_tunnels
    restart: unless-stopped
    network_mode: host
    environment:
      - CLOUDFLARE_TOKEN
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 100M