services:
  actual_server:
    image: actualbudget/actual-server:26.2.1-alpine
    container_name: actual
    ports:
      - "5006:5006"
    environment:
      # Uncomment any of the lines below to set configuration options.
       - ACTUAL_HTTPS_KEY=/data/selfhost.key
       - ACTUAL_HTTPS_CERT=/data/selfhost.crt
       - ACTUAL_PORT=5006
       - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
       - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - /mnt/media-nvm/Actual/data:/data
    healthcheck:
      # Enable health check for the instance
      test: ["CMD", "wget", "--no-check-certificate", "-qO-", "https://0.0.0.0:5006/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
