services:
  transmission:
    image: "lscr.io/linuxserver/transmission:4.0.5-r1-ls234"
    container_name: transmission
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - /mnt/media/Transmission/config:/config
      - /mnt/media/Transmission/downloads:/downloads
      - /mnt/media/Transmission/watch:/watch