version: '3'

services:
  db:
    image: postgres:15
    container_name: joplin-db
    volumes:
      - /media/Joplin/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - /media/Joplin/db.env
  app:
    image: joplin/server:3.5.2
    container_name: joplin-app
    depends_on:
      - db
    ports:
      - "22300:22300"
    restart: unless-stopped
    env_file:
      - /media/Joplin/app.env
